- name: Set up Let's Encrypt for {{ site_host }}
  include_tasks: "certbot.yml"
  vars:
    certbot_domain: "{{ site_host }}"
    certbot_email: "{{ email_address }}"
    certbot_flags: ""

- name: Set up Let's Encrypt for {{ site_host }} aliases
  include_tasks: "certbot.yml"
  vars:
    certbot_email: "{{ email_address }}"
    certbot_flags: ""
  loop: "{{ aliases }}"
  loop_control:
    loop_var: certbot_domain

- name: Create webroot
  ansible.builtin.file:
    path: /var/www/{{ site_name }}
    mode: "0775"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    recurse: true
    state: directory
  become: true

- name: Synchronize site to remote
  ansible.posix.synchronize:
    src: ../src/
    dest: /var/www/{{ site_name }}

- name: Update ownership of webroot
  ansible.builtin.file:
    path: /var/www/{{ site_name }}
    mode: "0775"
    owner: "{{ site_name }}"
    group: "{{ site_name }}"
    state: directory
    recurse: true
  become: true

- name: Create nginx site file
  ansible.builtin.template:
    src: ../files/nginx
    dest: /etc/nginx/sites-available/{{ site_name }}
    owner: root
    group: root
    mode: "0744"
  become: true
  register: nginx_site

- name: Stat nginx site symlink
  ansible.builtin.stat: 
    path: /etc/nginx/sites-enabled/{{ site_name }}
  become: true
  register: nginx_site_stat

- name: Create symlink for nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ site_name }}
    dest: /etc/nginx/sites-enabled/{{ site_name }}
    owner: root
    group: root
    mode: "0744"
    state: link
  become: true
  when: not nginx_site_stat.stat.exists

- name: Verify nginx site files
  ansible.builtin.command: nginx -t
  become: true
  when: nginx_site.changed

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
    scope: system
    enabled: true
  become: true
  when: nginx_site.changed

- name: Grant user {{ site_name }} certificate read access
  ansible.posix.acl:
    path: /etc/letsencrypt/live
    entity: "{{ site_name }}"
    etype: user
    permissions: rx
    state: present
  become: true

- name: Grant user {{ site_name }} certificate read access
  ansible.posix.acl:
    path: /etc/letsencrypt/live/{{ site_host }}
    entity: "{{ site_name }}"
    etype: user
    recursive: true
    permissions: rx
    state: present
  become: true

- name: Grant user {{ site_name }} certificate read access
  ansible.posix.acl:
    path: /etc/letsencrypt/archive
    entity: "{{ site_name }}"
    etype: user
    permissions: rx
    state: present
  become: true

- name: Grant user {{ site_name }} certificate read access
  ansible.posix.acl:
    path: /etc/letsencrypt/archive/{{ site_host }}
    entity: "{{ site_name }}"
    etype: user
    recursive: true
    permissions: rx
    state: present
  become: true